/*
@author: Laurie MAVOUNGOU, JK AI CEO, lmavoungou@outlook.be*/

DROP DATABASE IF EXISTS RIRAGTEST;

CREATE DATABASE RIRAGTEST;
USE RIRAGTEST;

CREATE TABLE file (
    file_id VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    semantic_summary TEXT NOT NULL,
    grade FLOAT NOT NULL,
    comments TEXT NOT NULL,
    CONSTRAINT file_pk PRIMARY KEY (file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*INSERT INTO file(file_id, file_name, content, semantic_sumary, grade, comments)
VALUES
('DOC-001', 'consistency_guidelines.txt', 'The multi-round validation loop checks model responses against persistent evidence using database primary keys.', 'Defines multi-round contradiction detection and evidence grounding.', 9.5, 'Approved by lead engineer.'),
('DOC-002', 'agent_safety.txt', 'Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures.', 'Autonomous agent safety and consistency rules.', 8.8, 'Needs minor revision on edge cases.');
 Upcoming push for scaling tests. Need to make the payload heavier than the summary
 */

INSERT INTO file(file_id, file_name, content, semantic_summary, grade, comments)
VALUES
('DOC-001', '001_consistency_guidelines.txt', 'The multi-round validation loop checks model responses against persistent evidence using database primary keys. The multi-round validation loop checks model responses against persistent evidence using database primary keys. The multi-round validation loop checks model responses against persistent evidence using database primary keys. The multi-round validation loop checks model responses against persistent evidence using database primary keys. The multi-round validation loop checks model responses against persistent evidence using database primary keys. The multi-round validation loop checks model responses against persistent evidence using database primary keys. The multi-round validation loop checks model responses against persistent evidence using database primary keys.', 'Defines multi-round contradiction detection and evidence grounding.', 8.0, 'Approved by lead engineer.'),
('DOC-002', '002_agent_safety.txt', 'Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures. Frontier autonomous agents must maintain structural consistency to prevent cascading decision failures.', 'Autonomous agent safety and consistency rules.', 8.5, 'Needs minor revision on edge cases.'),
('DOC-003', '003_rag_architecture.txt', 'Relational-Indexed Retrieval-Augmented Generation decouples vector search from authoritative records using foreign keys. Relational-Indexed Retrieval-Augmented Generation decouples vector search from authoritative records using foreign keys. Relational-Indexed Retrieval-Augmented Generation decouples vector search from authoritative records using foreign keys. Relational-Indexed Retrieval-Augmented Generation decouples vector search from authoritative records using foreign keys. Relational-Indexed Retrieval-Augmented Generation decouples vector search from authoritative records using foreign keys. Relational-Indexed Retrieval-Augmented Generation decouples vector search from authoritative records using foreign keys. Relational-Indexed Retrieval-Augmented Generation decouples vector search from authoritative records using foreign keys. Relational-Indexed Retrieval-Augmented Generation decouples vector search from authoritative records using foreign keys.', 'Overview of RI-RAG architectural decoupling.', 9.8, 'Production ready.'),
('DOC-004', '004_vector_optimization.txt', 'By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced. By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced. By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced. By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced. By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced. By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced. By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced. By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced. By storing only chunk IDs and embeddings in vector indices, RAM footprint is significantly reduced.', 'Memory optimization strategies for vector databases.', 9.7, 'Requires further RAM profiling.'),
('DOC-005', '005_rbac_security.txt', 'Role-Based Access Control is enforced at the database boundary via a privileged service account. Role-Based Access Control is enforced at the database boundary via a privileged service account. Role-Based Access Control is enforced at the database boundary via a privileged service account. Role-Based Access Control is enforced at the database boundary via a privileged service account. Role-Based Access Control is enforced at the database boundary via a privileged service account. Role-Based Access Control is enforced at the database boundary via a privileged service account. Role-Based Access Control is enforced at the database boundary via a privileged service account. Role-Based Access Control is enforced at the database boundary via a privileged service account.', 'Database-level access control mechanisms.', 8.7, 'Compliant with security standards.'),
('DOC-006', '006_audit_logging.txt', 'All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability. All retrieval requests and relational hydration steps must generate immutable audit logs for traceability.', 'Audit trail requirements for AI retrieval pipelines.', 8.2, 'Standardized across services.'),
('DOC-007', '007_adversarial_robustness.txt', 'Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations. Neural networks must incorporate adversarial training loops to resist gradient-based input perturbations.', 'Adversarial machine learning defense pipelines.', 8.7, 'Under active evaluation.'),
('DOC-008', '008_federated_privacy.txt', 'Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data. Federated learning enables decentralized model updates without exposing raw institutional data.', 'Privacy-preserving model aggregation techniques.', 9.4, 'Validated on medical datasets.'),
('DOC-009', '009_latency_benchmarks.txt', 'Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups. Network round-trips to relational databases introduce a measurable latency trade-off compared to in-memory lookups.', 'Query latency analysis for hybrid retrieval.', 9.3, 'Optimizing connection pooling.'),
('DOC-010', '010_code_based_crypto.txt', 'Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage. Quasi-cyclic error-correcting codes provide post-quantum cryptographic resilience for secure record storage.', 'Code-based cryptosystems and error correction.', 9.2, 'Reviewed by crypto team.'),
('DOC-011', '011_edge_ai_integration.txt', 'Edge AI devices require lightweight quantization to maintain real-time inference constraints. Edge AI devices require lightweight quantization to maintain real-time inference constraints. Edge AI devices require lightweight quantization to maintain real-time inference constraints. Edge AI devices require lightweight quantization to maintain real-time inference constraints. Edge AI devices require lightweight quantization to maintain real-time inference constraints. Edge AI devices require lightweight quantization to maintain real-time inference constraints. Edge AI devices require lightweight quantization to maintain real-time inference constraints.', 'Edge device quantization rules.', 9.1, 'Approved for embedded deployment.'),
('DOC-012', '012_context_pruning.txt', 'Context window pruning algorithms eliminate redundant tokens prior to relational hydration steps. Context window pruning algorithms eliminate redundant tokens prior to relational hydration steps. Context window pruning algorithms eliminate redundant tokens prior to relational hydration steps. Context window pruning algorithms eliminate redundant tokens prior to relational hydration steps. Context window pruning algorithms eliminate redundant tokens prior to relational hydration steps. Context window pruning algorithms eliminate redundant tokens prior to relational hydration steps.', 'Context pruning and token efficiency.', 8.9, 'Needs benchmark validation.'),
('DOC-013', '013_distributed_caching.txt', 'Distributed Redis caching layers minimize database round-trip latency for frequently accessed records. Distributed Redis caching layers minimize database round-trip latency for frequently accessed records. Distributed Redis caching layers minimize database round-trip latency for frequently accessed records. Distributed Redis caching layers minimize database round-trip latency for frequently accessed records. Distributed Redis caching layers minimize database round-trip latency for frequently accessed records. Distributed Redis caching layers minimize database round-trip latency for frequently accessed records.', 'Redis caching for hybrid retrieval pipelines.', 9.4, 'Production ready.');

CREATE USER 'test_user'@'localhost' IDENTIFIED BY '';
-- Grant restricted read-only access to the RIRAGTEST database only
GRANT SELECT ON RIRAGTEST.* TO 'test_user'@'localhost';

-- Flush privileges to apply changes
FLUSH PRIVILEGES;